"""End-to-end integration tests for the ingestion pipeline (US-023).

Covers the full path fetch -> normalize -> persist -> query as one flow,
plus dedicated checks for persisted-data validity, referential integrity
(FK constraints) and duplicate handling (upsert). All tests run against an
isolated SQLite in-memory database for speed.
"""

from unittest.mock import patch

import pytest
from sqlalchemy import create_engine
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session, sessionmaker

from app.database.connection import get_db_session  # noqa: F401  (registers FK pragma)
from app.database.models import Base, Country, Language
from app.database.repository import CountryRepository
from app.scripts.ingest import ingest_countries

RAW_BRAZIL = {
    "names": {"common": "Brazil", "official": "Federative Republic of Brazil"},
    "codes": {"alpha_2": "BR", "alpha_3": "BRA"},
    "region": "Americas",
    "subregion": "South America",
    "population": 215313498,
    "area": {"kilometers": 8514877.0},
    "coordinates": {"lat": -15.793889, "lng": -47.882778},
    "languages": [{"name": "Portuguese"}],
    "currencies": [{"code": "BRL", "name": "Brazilian real"}],
    "timezones": ["UTC-03:00"],
}

RAW_FRANCE = {
    "names": {"common": "France", "official": "French Republic"},
    "codes": {"alpha_2": "FR", "alpha_3": "FRA"},
    "region": "Europe",
    "population": 67750000,
    "area": {"kilometers": 551695.0},
    "languages": [{"name": "French"}],
    "currencies": [{"code": "EUR", "name": "Euro"}],
    "timezones": ["UTC+01:00"],
}


class TestFullPipelineFetchNormalizePersistQuery:
    """Fetch (mocked HTTP) -> normalize -> persist -> query, as one flow."""

    def test_full_pipeline_end_to_end(self, in_memory_session: Session) -> None:
        """Verify a country fetched from the API is queryable after ingestion.

        Why: Unit tests cover each stage in isolation; this proves the
        stages compose correctly end to end, against a real (in-memory)
        database rather than mocks of the repository layer.
        """
        with patch(
            "app.scripts.ingest.fetch_countries",
            return_value=[RAW_BRAZIL, RAW_FRANCE],
        ):
            report = ingest_countries(session=in_memory_session)

        assert report.status == "success"
        assert report.inserted == 2

        repo = CountryRepository(in_memory_session)
        brazil = repo.get_by_iso2("BR")

        assert brazil is not None
        assert brazil.name_common == "Brazil"
        assert brazil.population == 215313498
        assert len(brazil.languages) == 1
        assert brazil.languages[0].language_name == "Portuguese"
        assert repo.count_all() == 2


class TestPersistedDataValidation:
    """Validate that persisted rows match what was ingested, field for field."""

    def test_persisted_country_matches_source_data(
        self, in_memory_session: Session
    ) -> None:
        """Verify every scalar field survives the fetch->persist round trip."""
        with patch("app.scripts.ingest.fetch_countries", return_value=[RAW_BRAZIL]):
            ingest_countries(session=in_memory_session)

        country = (
            in_memory_session.query(Country).filter(Country.iso_code_2 == "BR").one()
        )

        assert country.name_official == "Federative Republic of Brazil"
        assert country.iso_code_3 == "BRA"
        assert country.region == "Americas"
        assert country.subregion == "South America"
        assert float(country.area) == 8514877.0
        assert float(country.latitude) == pytest.approx(-15.793889)
        assert float(country.longitude) == pytest.approx(-47.882778)

    def test_persisted_country_has_generated_id_and_timestamps(
        self, in_memory_session: Session
    ) -> None:
        """Verify autogenerated fields (id, created_at, updated_at) are set."""
        with patch("app.scripts.ingest.fetch_countries", return_value=[RAW_BRAZIL]):
            ingest_countries(session=in_memory_session)

        country = (
            in_memory_session.query(Country).filter(Country.iso_code_2 == "BR").one()
        )

        assert country.id is not None and country.id > 0
        assert country.created_at is not None
        assert country.updated_at is not None


class TestReferentialIntegrity:
    """FK constraint enforcement between Country and its related entities."""

    def test_related_entity_rejects_nonexistent_country_id(self) -> None:
        """Verify inserting a Language with a dangling country_id fails.

        Why: SQLite does not enforce foreign keys unless PRAGMA foreign_keys
        is explicitly enabled per connection; this proves that pragma is
        actually wired up (app.database.connection), not just declared in
        the ORM models.

        Uses its own standalone engine/session (own commit/rollback
        lifecycle) rather than the shared `in_memory_session` fixture,
        since this test intentionally triggers a failed commit and a
        session sharing the fixture's externally-managed transaction
        would leave that transaction in an inconsistent state afterwards.
        """
        engine = create_engine(
            "sqlite:///:memory:", connect_args={"check_same_thread": False}
        )
        Base.metadata.create_all(engine)
        session = sessionmaker(bind=engine)()

        try:
            session.add(
                Language(country_id=999_999, language_code="xx", language_name="Test")
            )

            with pytest.raises(IntegrityError, match="FOREIGN KEY constraint failed"):
                session.commit()
        finally:
            session.close()
            engine.dispose()

    def test_deleting_country_cascades_to_related_entities(
        self, in_memory_session: Session
    ) -> None:
        """Verify deleting a country removes its languages/currencies/timezones.

        Why: Confirms the ondelete=CASCADE FK behavior end to end, using
        real ingested data rather than hand-built fixtures.
        """
        with patch("app.scripts.ingest.fetch_countries", return_value=[RAW_BRAZIL]):
            ingest_countries(session=in_memory_session)

        repo = CountryRepository(in_memory_session)
        brazil = repo.get_by_iso2("BR")
        country_id = brazil.id

        repo.delete(country_id)

        remaining_languages = (
            in_memory_session.query(Language)
            .filter(Language.country_id == country_id)
            .count()
        )
        assert remaining_languages == 0
        assert repo.get_by_id(country_id) is None


class TestDuplicateHandlingUpsert:
    """Re-running ingestion must upsert, never duplicate."""

    def test_reingesting_same_country_does_not_duplicate(
        self, in_memory_session: Session
    ) -> None:
        """Verify running the pipeline twice for the same country updates it in place."""
        with patch("app.scripts.ingest.fetch_countries", return_value=[RAW_BRAZIL]):
            first = ingest_countries(session=in_memory_session)

        updated_raw = dict(RAW_BRAZIL)
        updated_raw["population"] = 220_000_000

        with patch("app.scripts.ingest.fetch_countries", return_value=[updated_raw]):
            second = ingest_countries(session=in_memory_session)

        repo = CountryRepository(in_memory_session)

        assert first.inserted == 1
        assert second.inserted == 0
        assert second.updated == 1
        assert repo.count_all() == 1
        assert repo.get_by_iso2("BR").population == 220_000_000

    def test_duplicate_iso_codes_within_same_batch_only_persist_once(
        self, in_memory_session: Session
    ) -> None:
        """Verify a batch containing the same country twice results in one row."""
        with patch(
            "app.scripts.ingest.fetch_countries",
            return_value=[RAW_BRAZIL, RAW_BRAZIL],
        ):
            report = ingest_countries(session=in_memory_session)

        repo = CountryRepository(in_memory_session)

        assert report.status == "success"
        assert repo.count_all() == 1
